use quote::ToTokens;
use std::collections::HashMap;
use syn::{ExprClosure, Field, PathSegment, Token, Variant, punctuated::Punctuated};

use crate::visitors::schema_finder::SchemaType;

/// Information about a validated schema
#[derive(Clone)]
pub struct SchemaInfo<'ast> {
    /// The schema type (struct or enum)
    pub schema_type: Option<SchemaType<'ast>>,
    /// Full path to the schema including module hierarchy
    pub path: Punctuated<PathSegment, Token![::]>,
<<<<<<< HEAD
<<<<<<< HEAD
    pub schema_key: Option<KeyType<'ast>>,
=======
=======
    /// Key information for the schema
>>>>>>> 4740b930844447b717a06adb472169f5fb202c37
    pub schema_key: Option<KeyInfo<'ast>>,
>>>>>>> 9ebb163c7b1984ab70d5bbe2ab7aa48824850724
}

impl<'ast> SchemaInfo<'ast> {
    /// Create a new empty schema info
    pub fn new() -> Self {
        Self {
            schema_type: None,
            path: Punctuated::new(),
            schema_key: None,
        }
    }

    /// Check if this schema info is complete and valid
    pub fn is_valid(&self) -> bool {
        self.schema_type.is_some() && self.schema_key.is_some()
    }

    /// Get the schema name
    pub fn name(&self) -> Option<&syn::Ident> {
        self.schema_type.as_ref().map(|st| st.identity())
    }

    /// Get the full path as a string
    pub fn path_string(&self) -> String {
        self.path
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect::<Vec<_>>()
            .join("::")
    }
}

impl<'ast> Default for SchemaInfo<'ast> {
    fn default() -> Self {
        Self::new()
    }
}

/// Information about a field key including its position
#[derive(Clone)]
pub struct FieldKeyInfo<'ast> {
    pub field: &'ast Field,
    pub index: Option<usize>, // For tuple variants, this is the field index
}

/// Type of key used by a schema
#[derive(Clone)]
pub enum KeyType<'ast> {
    /// Keys are individual fields marked with #[key]
    FieldKeys(HashMap<Option<&'ast Variant>, FieldKeyInfo<'ast>>),
    /// Key is a closure defined on the schema itself
    SchemaKey(&'ast ExprClosure),
    /// Key is generated by a function reference
    KeyFunction(String),
}

impl<'ast> KeyType<'ast> {
    /// Check if this is a field key type
    pub fn is_field_keys(&self) -> bool {
        matches!(self, KeyType::FieldKeys(_))
    }

    /// Check if this is a schema key type
    pub fn is_schema_key(&self) -> bool {
        matches!(self, KeyType::SchemaKey(_))
    }

    /// Check if this is a key function type
    pub fn is_key_function(&self) -> bool {
        matches!(self, KeyType::KeyFunction(_))
    }

    /// Get field keys if this is a field key type
    pub fn as_field_keys(&self) -> Option<&HashMap<Option<&'ast Variant>, FieldKeyInfo<'ast>>> {
        match self {
            KeyType::FieldKeys(fields) => Some(fields),
            _ => None,
        }
    }

    /// Get schema key if this is a schema key type
    pub fn as_schema_key(&self) -> Option<&'ast ExprClosure> {
        match self {
            KeyType::SchemaKey(closure) => Some(closure),
            _ => None,
        }
    }

    /// Get key function if this is a key function type
    pub fn as_key_function(&self) -> Option<&str> {
        match self {
            KeyType::KeyFunction(func_name) => Some(func_name),
            _ => None,
        }
    }
}

<<<<<<< HEAD
pub(crate) mod schema_finder {
    use std::collections::HashMap;

    use syn::{
        Attribute, Field, Fields, Generics, Ident, Item, ItemEnum, ItemStruct, Variant, Visibility,
        punctuated::Punctuated, spanned::Spanned, token::Comma,
    };

    #[derive(Clone, Copy)]
    pub(crate) enum SchemaType<'ast> {
        Struct(&'ast ItemStruct),
        Enum(&'ast ItemEnum),
    }

    impl<'ast> SchemaType<'ast> {
        pub(crate) fn attributes<'b>(&'b self) -> &'ast Vec<Attribute> {
            match self {
                SchemaType::Struct(item_struct) => &item_struct.attrs,
                SchemaType::Enum(item_enum) => &item_enum.attrs,
            }
        }

        pub(crate) fn visibility<'b>(&'b self) -> &'ast Visibility {
            match self {
                SchemaType::Struct(item_struct) => &item_struct.vis,
                SchemaType::Enum(item_enum) => &item_enum.vis,
            }
        }
        pub(crate) fn identity<'b>(&'b self) -> &'ast Ident {
            match self {
                SchemaType::Struct(item_struct) => &item_struct.ident,
                SchemaType::Enum(item_enum) => &item_enum.ident,
            }
        }

        pub(crate) fn generics<'b>(&'b self) -> &'ast Generics {
            match self {
                SchemaType::Struct(item_struct) => &item_struct.generics,
                SchemaType::Enum(item_enum) => &item_enum.generics,
            }
        }

        pub(crate) fn variants<'b>(&'b self) -> Option<&'ast Punctuated<Variant, Comma>> {
            match self {
                SchemaType::Struct(_) => None,
                SchemaType::Enum(item_enum) => Some(&item_enum.variants),
            }
        }

        pub(crate) fn fields<'b>(&'b self) -> HashMap<Option<&'ast Variant>, &'ast Fields> {
            match self {
                SchemaType::Struct(item_struct) => {
                    let mut res: HashMap<Option<&'ast Variant>, &'ast syn::Fields> = HashMap::new();
                    res.insert(None, &item_struct.fields);
                    res
                }
                SchemaType::Enum(item_enum) => {
                    let mut res: HashMap<Option<&Variant>, &syn::Fields> = HashMap::new();
                    item_enum.variants.iter().for_each(|v| {
                        res.insert(Some(v), &v.fields);
                    });
                    res
                }
            }
        }
    }

    impl<'a> TryFrom<&'a Item> for SchemaType<'a> {
        type Error = syn::Error;

        fn try_from(value: &'a Item) -> Result<Self, Self::Error> {
            match value {
                Item::Enum(item_enum) => Ok(SchemaType::Enum(item_enum)),
                Item::Struct(item_struct) => Ok(SchemaType::Struct(item_struct)),
                _ => Err(syn::Error::new(
                    value.span(),
                    "Schema can only be an Enum or a Struct",
                )),
            }
        }
    }
}

pub(crate) mod schema_validator {
    use crate::visitors::utils::SchemaType;

    pub(crate) fn contains_netabase_derive<'a>(schema_type: &SchemaType<'a>) -> bool {
        schema_type
            .attributes()
            .iter()
            .any(|att| att.path().is_ident("Clone"))
    }
}
pub(crate) mod key_finder {

    use crate::visitors::utils::KeyType;
    use syn::{Expr, Field, Fields, Item, Meta};

    use crate::visitors::utils::schema_finder::SchemaType;

    pub(crate) fn get_schema_field_keys<'ast: 'b, 'b>(
        schema: &'b SchemaType<'ast>,
    ) -> KeyType<'ast> {
        KeyType::FieldKeys(
            schema
                .fields()
                .iter()
                .filter_map(
                    |(var, fie)| match (var, check_fields_for_key(fie.clone())) {
                        (None, None) => panic!("Fielded structs need a key field"),
                        (_, Some(_)) => Some((*var, *fie)),
                        (Some(_), None) => {
                            panic!("Every Variant needs a key");
                            None
=======
impl ToTokens for KeyType<'_> {
    fn to_tokens(&self, tokens: &mut proc_macro2::TokenStream) {
        match self {
<<<<<<< HEAD
            KeyType::FieldKeys(hash_map) => {
                let stream = hash_map.iter().filter_map(|(o, f)| {
                    o.as_ref().map(|op| {
                        quote! {
                            #op: #f,
>>>>>>> 9ebb163c7b1984ab70d5bbe2ab7aa48824850724
=======
            KeyType::FieldKeys(field_map) => {
                let field_tokens: Vec<proc_macro2::TokenStream> = field_map
                    .iter()
                    .filter_map(|(variant_opt, field_info)| {
                        let field = field_info.field;
                        if let Some(variant) = variant_opt {
                            Some(quote::quote! {
                                stringify!(#variant: #field)
                            })
                        } else {
                            Some(quote::quote! {
                                stringify!(#field)
                            })
>>>>>>> 4740b930844447b717a06adb472169f5fb202c37
                        }
                    })
                    .collect();

                tokens.extend(quote::quote! {
                    #(#field_tokens)*
                });
            }
            KeyType::SchemaKey(closure) => {
                closure.to_tokens(tokens);
            }
            KeyType::KeyFunction(func_name) => {
                tokens.extend(quote::quote! {
                    stringify!(#func_name)
                });
            }
        }
    }
}

/// Information about keys for a schema
#[derive(Clone, Default)]
pub struct KeyInfo<'ast> {
    /// The type of key generation to use
    pub generation_type: Option<KeyType<'ast>>,
}

impl<'ast> KeyInfo<'ast> {
    /// Create a new empty key info
    pub fn new() -> Self {
        Self::default()
    }

    /// Create key info with a specific generation type
    pub fn with_generation_type(generation_type: KeyType<'ast>) -> Self {
        Self {
            generation_type: Some(generation_type),
        }
    }

    /// Check if this key info is valid (has a generation type)
    pub fn is_valid(&self) -> bool {
        self.generation_type.is_some()
    }

    /// Get the generation type
    pub fn generation_type(&self) -> Option<&KeyType<'ast>> {
        self.generation_type.as_ref()
    }

    /// Check if this uses field keys
    pub fn uses_field_keys(&self) -> bool {
        matches!(self.generation_type, Some(KeyType::FieldKeys(_)))
    }

    /// Check if this uses a schema key
    pub fn uses_schema_key(&self) -> bool {
        matches!(self.generation_type, Some(KeyType::SchemaKey(_)))
    }

    /// Check if this uses a key function
    pub fn uses_key_function(&self) -> bool {
        matches!(self.generation_type, Some(KeyType::KeyFunction(_)))
    }
}

/// Builder pattern for creating SchemaInfo
pub struct SchemaInfoBuilder<'ast> {
    info: SchemaInfo<'ast>,
}

impl<'ast> SchemaInfoBuilder<'ast> {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            info: SchemaInfo::new(),
        }
    }

    /// Set the schema type
    pub fn with_schema_type(mut self, schema_type: SchemaType<'ast>) -> Self {
        self.info.schema_type = Some(schema_type);
        self
    }

    /// Set the path
    pub fn with_path(mut self, path: Punctuated<PathSegment, Token![::]>) -> Self {
        self.info.path = path;
        self
    }

    /// Set the key info
    pub fn with_key_info(mut self, key_info: KeyInfo<'ast>) -> Self {
        self.info.schema_key = Some(key_info);
        self
    }

    /// Build the final SchemaInfo
    pub fn build(self) -> SchemaInfo<'ast> {
        self.info
    }
}

impl<'ast> Default for SchemaInfoBuilder<'ast> {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use syn::parse_quote;

    #[test]
    fn test_schema_info_creation() {
        let info = SchemaInfo::new();
        assert!(!info.is_valid());
        assert!(info.name().is_none());
    }

    #[test]
    fn test_key_info_creation() {
        let key_info = KeyInfo::new();
        assert!(!key_info.is_valid());

        let field_keys = HashMap::new();
        let key_info_with_type = KeyInfo::with_generation_type(KeyType::FieldKeys(field_keys));
        assert!(key_info_with_type.is_valid());
        assert!(key_info_with_type.uses_field_keys());
    }

    #[test]
    fn test_schema_info_builder() {
        let item: syn::Item = parse_quote! {
            struct TestSchema {
                id: u64,
            }
        };

        let schema_type = SchemaType::try_from(&item).unwrap();
        let path: Punctuated<PathSegment, Token![::]> = parse_quote!(test::TestSchema);
        let key_info = KeyInfo::new();

        let info = SchemaInfoBuilder::new()
            .with_schema_type(schema_type)
            .with_path(path)
            .with_key_info(key_info)
            .build();

        assert!(info.schema_type.is_some());
        assert_eq!(info.path.len(), 2);
    }
}
