[package]
name = "netabase"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = "0.56.0"
netabase_store = {path = "../netabase_store"}
strum = "*"
bitflags = { version = "2.10.0", features = ["serde", "serde_core"] }
serde = { version = "1.0.228", features = ["derive", "serde_derive", "std"] }
serde-big-array = "0.5.1"
redb = "3.1.0"

[dev-dependencies]
netabase_store = {path = "../netabase_store"}
