[package]
name = "netabase"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = "0.56.0"
netabase_store = {path = "../netabase_store"}
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
