[package]
name = "netabase"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "netabase_macros"
, "test_macros"]

[dependencies]
anyhow = "1.0.100"
bincode = { version = "2.0", features = ["derive", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
derive_more = { version = "2.0.1", features = ["from", "try_into"] }
libp2p = { version = "0.56.0", features = ["kad"] }
native_db = { version = "*", features = ["tokio"] }
native_model = "0.4.20"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
test_macros = { path = "test_macros" }
tempfile = "3.0"
