[package]
name = "netabase"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["netabase_macros", "test_macros"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.98"
bincode = { version = "2.0.1", features = ["serde"] }
clap = { version = "4.4", features = ["derive", "env"] }
env_logger = "0.11.8"
envy = "0.4"
libp2p = { version = "*", features = [
    "full",
    "identify",
    "kad",
    "metrics",
    "quic",
] }
log = "0.4.27"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
sled = "0.34.7"
smallvec = { version = "1.15.1", features = ["bincode", "impl_bincode"] }
tokio = { version = "1.45.1", features = ["full"] }
