use crate::traits::NetabaseModelKey;
use bincode::{Decode, Encode};
use std::fmt::Debug;

/// Represents a relational link that can either store a primary key or the actual object
/// for lazy fetching scenarios.
#[derive(Debug, Clone, Encode, Decode, serde::Serialize, serde::Deserialize)]
pub enum RelationalLink<K, T>
where
    K: NetabaseModelKey,
    T: Clone + Debug,
{
    /// Contains only the primary key of the related object
    Key(K),
    /// Contains the actual related object (loaded/resolved)
    Object(T),
}

impl<K, T> RelationalLink<K, T>
where
    K: NetabaseModelKey,
    T: Clone + Debug,
{
    /// Create a new RelationalLink with just a key
    pub fn from_key(key: K) -> Self {
        Self::Key(key)
    }

    /// Create a new RelationalLink with the actual object
    pub fn from_object(object: T) -> Self {
        Self::Object(object)
    }

    /// Get the key if this link contains one
    pub fn key(&self) -> Option<&K> {
        match self {
            Self::Key(k) => Some(k),
            Self::Object(_) => None,
        }
    }

    /// Get the object if this link contains one
    pub fn object(&self) -> Option<&T> {
        match self {
            Self::Key(_) => None,
            Self::Object(obj) => Some(obj),
        }
    }

    /// Check if this link is resolved (contains an object)
    pub fn is_resolved(&self) -> bool {
        matches!(self, Self::Object(_))
    }

    /// Check if this link is unresolved (contains only a key)
    pub fn is_unresolved(&self) -> bool {
        matches!(self, Self::Key(_))
    }

    /// Resolve the link by replacing the key with an object (consuming version)
    pub fn resolve(self, object: T) -> Self {
        Self::Object(object)
    }

    /// Resolve the link in-place by mutating it to contain the object and return a reference
    pub fn resolve_mut(&mut self, object: T) -> &T {
        *self = Self::Object(object);
        match self {
            Self::Object(obj) => obj,
            _ => unreachable!("We just set it to Object"),
        }
    }

    /// Resolve the link in-place if it's currently unresolved, return reference to object
    pub fn resolve_if_unresolved(&mut self, object: T) -> &T {
        if self.is_unresolved() {
            self.resolve_mut(object)
        } else {
            self.object()
                .expect("Link should be resolved at this point")
        }
    }

    /// Convert to key, consuming the link
    pub fn into_key(self) -> Option<K> {
        match self {
            Self::Key(k) => Some(k),
            Self::Object(_) => None,
        }
    }

    /// Convert to object, consuming the link
    pub fn into_object(self) -> Option<T> {
        match self {
            Self::Key(_) => None,
            Self::Object(obj) => Some(obj),
        }
    }

    /// Get a mutable reference to the object if resolved, or None if unresolved
    pub fn object_mut(&mut self) -> Option<&mut T> {
        match self {
            Self::Key(_) => None,
            Self::Object(obj) => Some(obj),
        }
    }
}

impl<K, T> From<K> for RelationalLink<K, T>
where
    K: NetabaseModelKey,
    T: Clone + Debug,
{
    fn from(key: K) -> Self {
        Self::Key(key)
    }
}

impl<K, T> PartialEq for RelationalLink<K, T>
where
    K: NetabaseModelKey + PartialEq,
    T: Clone + Debug + PartialEq,
{
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::Key(k1), Self::Key(k2)) => k1 == k2,
            (Self::Object(obj1), Self::Object(obj2)) => obj1 == obj2,
            _ => false,
        }
    }
}

// Type aliases are now generated by the NetabaseModel derive macro
