[package]
name = "macro_exports"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bincode = { version ="*", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from", "try_into"] }
enum_unwrapper = "0.1.2"
libp2p-kad = "0.48.0"
unwrap-enum = "0.1.0"
