[package]
name = "example_usage"
version = "0.1.0"
edition = "2024"

[features]
default = ["libp2p"]
libp2p = ["dep:libp2p"]

[dependencies]
bincode.workspace = true
chrono.workspace = true
derive_more.workspace = true
env_logger.workspace = true
libp2p = { workspace = true, features = ["kad"], optional = true }
log.workspace = true
netabase = { version = "0.1.0", path = ".." }
netabase_macros = { version = "0.1.0", path = "../netabase_store/netabase_macros" }
netabase_store = { version = "0.1.0", path = "../netabase_store" }
serde.workspace = true
sled.workspace = true
strum.workspace = true
tempfile.workspace = true
tokio = "1.47.1"



# [[bin]]
# name = "advanced_queries"
# path = "src/bin/advanced_queries.rs"

# [[bin]]
# name = "blog_system"
# path = "src/bin/blog_system.rs"

# [[bin]]
# name = "getting_started"
# path = "src/bin/getting_started.rs"

# [[bin]]
# name = "netabase_basic_usage"
# path = "src/bin/netabase_basic_usage.rs"
