//! Network-capable definition trait for P2P systems.
//!
//! This module defines the `NetworkDefinition` trait, which extends `NetabaseDefinition`
//! with capabilities required for peer-to-peer networking and distributed systems.
//!
//! # Purpose
//!
//! While `NetabaseDefinition` handles local database operations, `NetworkDefinition`
//! adds the traits and types needed for:
//! - Advertising capabilities to peers
//! - Negotiating feature support
//! - Coordinating schema versions across nodes
//! - Managing network-specific metadata
//!
//! # Usage
//!
//! The `NetworkDefinition` trait is typically implemented via the `#[netabase_definition]`
//! macro when the `libp2p` feature is enabled. The macro generates:
//!
//! - A `DefinitionCapabilities` struct with fields for each model's capabilities
//! - Topic/subscription capability structs for grouped access control
//!
//! For concrete examples, see the `example` crate which demonstrates full usage
//! with the derive macros.
//!
//! # Trait Definition
//!
//! ```rust
//! use netabase_store::prelude::NetabaseDefinition;
//! use netabase_store::strum::IntoDiscriminant;
//!
//! /// The trait that network-capable definitions implement
//! pub trait NetworkDefinition: NetabaseDefinition
//! where
//!     <Self as IntoDiscriminant>::Discriminant: std::fmt::Debug + 'static,
//! {
//!     /// What capabilities this definition advertises to peers
//!     type DefinitionCapabilities;
//! }
//! ```

use netabase_store::prelude::NetabaseDefinition;
use netabase_store::strum::IntoDiscriminant;

/// Extension of `NetabaseDefinition` for network-capable definitions.
///
/// This trait adds support for advertising definition capabilities in a
/// peer-to-peer network, allowing nodes to discover what features and
/// models each peer supports.
///
/// # Associated Types
///
/// - `DefinitionCapabilities`: Type representing what features this definition
///   supports (e.g., which optional features are enabled, version numbers, etc.)
///
/// # Requirements
///
/// Implementations must also implement `NetabaseDefinition`, ensuring the
/// definition works both locally and in networked contexts.
///
/// # Implementation
///
/// This trait is typically implemented automatically by the `#[netabase_definition]`
/// macro when the `libp2p` feature is enabled. Manual implementation looks like:
///
/// ```text
/// // Generated by macro:
/// impl NetworkDefinition for MyDefinition {
///     type DefinitionCapabilities = MyDefinitionCapabilities;
/// }
///
/// // The capabilities struct is also generated:
/// pub struct MyDefinitionCapabilities {
///     pub user_capabilities: Vec<Capability<MyDefinition, User>>,
///     pub post_capabilities: Vec<Capability<MyDefinition, Post>>,
///     // ... one field per model
/// }
/// ```
pub trait NetworkDefinition: NetabaseDefinition
where
    <Self as IntoDiscriminant>::Discriminant: std::fmt::Debug,
    <Self as IntoDiscriminant>::Discriminant: 'static,
{
    /// Type representing the capabilities of this definition.
    ///
    /// This type should describe what features and versions this definition
    /// supports, allowing peers to determine compatibility.
    type DefinitionCapabilities;
}
