//! Definition Routing Helpers
//!
//! This module provides utilities for routing NetabaseDefinition variants
//! to their appropriate storage trees and handling conversions between
//! definitions and individual models.

use anyhow::Result;
use netabase_store::traits::{definition::NetabaseDefinitionTrait, model::NetabaseModelTrait};

/// Helper trait that bundles all required bounds for NetabaseDefinitionTrait
///
/// This makes it easier to work with definition types throughout the routing module
pub trait FullyBoundedDefinition: NetabaseDefinitionTrait
where
    <Self as strum::IntoDiscriminant>::Discriminant: AsRef<str>
        + Clone
        + Copy
        + std::fmt::Debug
        + std::fmt::Display
        + PartialEq
        + Eq
        + std::hash::Hash
        + strum::IntoEnumIterator
        + Send
        + Sync
        + 'static
        + std::str::FromStr,
{
}

// Blanket implementation for any type that satisfies the bounds
impl<D> FullyBoundedDefinition for D
where
    D: NetabaseDefinitionTrait,
    <D as strum::IntoDiscriminant>::Discriminant: AsRef<str>
        + Clone
        + Copy
        + std::fmt::Debug
        + std::fmt::Display
        + PartialEq
        + Eq
        + std::hash::Hash
        + strum::IntoEnumIterator
        + Send
        + Sync
        + 'static
        + std::str::FromStr,
{
}

/// Router trait for NetabaseDefinition types
///
/// This trait enables pattern matching on definition variants and routing
/// them to appropriate handlers. It's intended to be implemented via
/// macro generation for each definition type.
///
/// # Example
///
/// ```ignore
/// // Generated by #[derive(NetabaseRouter)]
/// impl DefinitionRouter<BlogDefinition> for BlogDefinition {
///     fn route_to_model<F>(&self, handler: &mut F) -> Result<()>
///     where
///         F: ModelHandler<BlogDefinition>,
///     {
///         match self {
///             BlogDefinition::User(user) => handler.handle_user(user),
///             BlogDefinition::Post(post) => handler.handle_post(post),
///             BlogDefinition::Comment(comment) => handler.handle_comment(comment),
///         }
///     }
/// }
/// ```
pub trait DefinitionRouter<D>
where
    D: NetabaseDefinitionTrait,
    <D as strum::IntoDiscriminant>::Discriminant: AsRef<str>
        + Clone
        + Copy
        + std::fmt::Debug
        + std::fmt::Display
        + PartialEq
        + Eq
        + std::hash::Hash
        + strum::IntoEnumIterator
        + Send
        + Sync
        + 'static
        + std::str::FromStr,
{
    /// Route the definition variant to the appropriate handler method
    ///
    /// This method performs pattern matching on the enum variant and calls
    /// the corresponding handler method with the inner model.
    fn route_to_model<F>(&self, handler: &mut F) -> Result<()>
    where
        F: ModelHandler<D>;

    // extract_model removed - would require TryFrom implementations to be generated by macro
}

/// Handler trait for processing different model types
///
/// Implementations of this trait define how to handle each model variant
/// from a NetabaseDefinition. This is typically used with `DefinitionRouter`
/// to enable type-safe routing.
///
/// # Example
///
/// ```ignore
/// struct RecordStoreHandler<'a> {
///     store: &'a mut NetabaseStore<BlogDefinition>,
/// }
///
/// impl<'a> ModelHandler<BlogDefinition> for RecordStoreHandler<'a> {
///     fn handle_user(&mut self, user: &User) -> Result<()> {
///         let record = UserRecordStore::encode_to_record(user)?;
///         self.store.put(record)?;
///         Ok(())
///     }
///
///     fn handle_post(&mut self, post: &Post) -> Result<()> {
///         let record = PostRecordStore::encode_to_record(post)?;
///         self.store.put(record)?;
///         Ok(())
///     }
///
///     // ... other handlers
/// }
/// ```
pub trait ModelHandler<D>
where
    D: NetabaseDefinitionTrait,
    <D as strum::IntoDiscriminant>::Discriminant: AsRef<str>
        + Clone
        + Copy
        + std::fmt::Debug
        + std::fmt::Display
        + PartialEq
        + Eq
        + std::hash::Hash
        + strum::IntoEnumIterator
        + Send
        + Sync
        + 'static
        + std::str::FromStr,
{
    /// Handle a model of any type supported by the definition
    ///
    /// This is a generic fallback that can be overridden for specific types
    fn handle<M>(&mut self, _model: &M) -> Result<()>
    where
        M: NetabaseModelTrait<D>,
        D: From<M>,
    {
        // Default implementation - can be overridden
        Err(anyhow::anyhow!(
            "Handler not implemented for model type: {}",
            std::any::type_name::<M>()
        ))
    }
}

// Utility functions removed to avoid circular trait bound issues
// Use codec functions from network::model_record_store::codec directly

/// Macro-generation helpers
///
/// These are used by the proc macro to generate routing code
#[doc(hidden)]
pub mod codegen {
    /// Helper struct for generating match arms in routing code
    pub struct VariantInfo {
        pub variant_name: String,
        pub model_type: String,
        pub handler_method: String,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Tests would be in integration tests with actual definition types
    #[test]
    fn test_utils_module_exists() {
        // Basic smoke test that the module compiles
        assert!(true);
    }
}
